/**
 * Site-wide constants and SEO helpers.
 *
 * `SITE_URL` is the single source of truth for absolute URLs (canonical tags,
 * Open Graph, sitemap, JSON-LD), and it is baked in at build time — there is no
 * server to work it out at request time, because the site deploys as an
 * assets-only Worker with no runtime code.
 *
 * The default below is the real production origin, committed deliberately. An
 * earlier version used a placeholder and required two build variables to be set
 * on every deploy, which meant a mis-set variable produced a site that quietly
 * advertised an origin that was not its own. A committed default cannot be
 * forgotten, and is visible in review.
 *
 * Override it when building for somewhere else — a custom domain, a staging
 * origin — by setting BOTH variables, since they are read by two processes:
 *
 *   VITE_SITE_URL=https://example.com SITE_URL=https://example.com pnpm build
 *
 * `scripts/preflight.mjs` validates the override; `src/core/site.test.ts`
 * keeps this constant in step with the copy in `scripts/generate-sitemap.mjs`.
 */

const DEFAULT_SITE_URL = 'https://cryptolab.istiaqahmed87.workers.dev';

/** Absolute origin, no trailing slash. */
/**
 * The repository. Used for the footer's source and "report an error" links:
 * a site that asks to be believed about cryptography needs a visible route for
 * telling it that it is wrong.
 */
export const REPO_URL = 'https://github.com/isti2415/cryptolab';

export const SITE_URL = (
  import.meta.env.VITE_SITE_URL || DEFAULT_SITE_URL
).replace(/\/$/, '');

export const SITE_NAME = 'CryptoLab';

export const SITE_TAGLINE = 'Cryptography, One Step at a Time';

/**
 * Meta description. Google truncates around 150–160 characters, so this stays
 * inside that; `SITE_DESCRIPTION_SOCIAL` is the shorter form for share cards,
 * where mobile previews cut off nearer 125.
 */
export const SITE_DESCRIPTION =
  'Watch real cryptographic algorithms transform real input step by step, then try your own keys in a live playground. Caesar to AES, RSA and ML-KEM.';

export const SITE_DESCRIPTION_SOCIAL =
  'Watch real ciphers work step by step, then try your own keys. Caesar to AES, RSA and ML-KEM.';

/** ISO 639-1 + region, for og:locale and <html lang>. */
export const SITE_LOCALE = 'en_US';

export const TWITTER_HANDLE = ''; // set if/when an account exists, e.g. '@cryptolab'

/**
 * Share image for a route.
 *
 * One card per page, generated by `pnpm og` into /public/og and committed. The
 * mapping is derived from the path rather than configured per page, so a new
 * algorithm gets the right image with no extra wiring; `scripts/verify-og.mjs`
 * fails the build if a route's card is missing.
 */
export function ogImageForPath(path: string): string {
  if (path === '/' || path === '') return '/og/home.png';
  const algorithm = path.match(/^\/a\/([\w-]+)\/?$/);
  if (algorithm) return `/og/a/${algorithm[1]}.png`;
  return '/og/home.png';
}

/** Build an absolute URL from a root-relative path. */
export function absoluteUrl(path: string): string {
  if (!path.startsWith('/')) path = `/${path}`;
  return `${SITE_URL}${path}`;
}

/**
 * Trim to a whole word within `max` characters, adding an ellipsis only when
 * something was actually dropped. A hard `slice()` cuts mid-word, which is
 * exactly what a search result should never show.
 */
export function clampText(text: string, max: number): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max - 1);
  const space = cut.lastIndexOf(' ');
  return `${(space > max * 0.6 ? cut.slice(0, space) : cut).replace(/[,;:.\s]+$/, '')}…`;
}
