/**
 * Generates the Open Graph share images into `public/og/`.
 *
 * One card per route: `public/og/home.png` plus `public/og/a/<id>.png`. Every
 * algorithm gets its own name, family, era and tagline on the card, so a link
 * to the AES page previews as AES rather than as a generic site banner.
 *
 * Why this runs by hand and commits its output, instead of running on every
 * build: rasterising needs a native module and a font decompressor, and putting
 * either of those in the Cloudflare Pages build makes a cosmetic feature able to
 * break a deploy. The images change only when an algorithm is added or renamed,
 * so they are treated like the vector fixtures — generated by a committed
 * script, checked in, and verified at build time by `scripts/verify-og.mjs`,
 * which fails loudly if a route has no card.
 *
 * Run: pnpm og
 */

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { Resvg } from '@resvg/resvg-js';
import { createServer } from 'vite';
import woff2 from 'wawoff2';

let TAGLINE = '';

const W = 1200;
const H = 630;
const OUT = 'public/og';

/* Dark-theme palette, lifted from tokens.css. Social cards are shown against
   both light and dark chrome, and the dark card holds up in either. */
const C = {
  bg: '#08090b',
  panel: '#14171c',
  border: '#2c313a',
  text: '#e6e9ef',
  muted: '#a8b1c0',
  dim: '#8b95a5',
  signal: '#35e0d0',
};

/* The site ships woff2, which resvg cannot read, so the same files are
   decompressed to TrueType in memory. Using the site's own font files rather
   than a second copy is what keeps the cards on-brand by construction. */
const FONT_FILES = [
  '@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-400-normal.woff2',
  '@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-600-normal.woff2',
  '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2',
  '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-500-normal.woff2',
];

/* resvg takes font *paths*, not buffers, so the decompressed faces are staged
   in a temp directory for the length of the run. */
async function loadFonts() {
  const dir = mkdtempSync(join(tmpdir(), 'cryptolab-og-'));
  const paths = [];
  for (const rel of FONT_FILES) {
    const ttf = Buffer.from(await woff2.decompress(readFileSync(join('node_modules', rel))));
    const out = join(dir, basename(rel).replace(/\.woff2$/, '.ttf'));
    writeFileSync(out, ttf);
    paths.push(out);
  }
  return { dir, paths };
}

/*
 * Wrapping without a text shaper. Plex Sans averages a little over half the
 * font size per character at these sizes; the caps ratio is higher, so uppercase
 * runs are charged more. Only used to decide line breaks, and the boxes below
 * leave enough slack that being a few percent out never clips.
 */
function widthOf(text, size, mono) {
  if (mono) return text.length * size * 0.6;
  let units = 0;
  for (const ch of text) {
    if (ch === ' ') units += 0.26;
    else if ('ilj.,;:!|\'`'.includes(ch)) units += 0.3;
    else if ('mwMW'.includes(ch)) units += 0.85;
    else if (ch >= 'A' && ch <= 'Z') units += 0.66;
    else units += 0.53;
  }
  return units * size;
}

function wrap(text, size, maxWidth, maxLines) {
  const words = text.split(/\s+/);
  const lines = [];
  let line = '';
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (widthOf(next, size) > maxWidth && line) {
      lines.push(line);
      line = word;
      if (lines.length === maxLines) break;
    } else {
      line = next;
    }
  }
  if (lines.length < maxLines && line) lines.push(line);
  if (lines.length === maxLines) {
    // Anything that did not fit is elided rather than silently dropped.
    const consumed = lines.join(' ');
    if (consumed.length < text.length - 1) {
      lines[maxLines - 1] = lines[maxLines - 1].replace(/[.,;:]?$/, '') + '…';
    }
  }
  return lines;
}

/** Shrink the title until it fits one line, down to a floor. */
function titleSize(text, maxWidth) {
  for (let size = 96; size > 44; size -= 2) {
    if (widthOf(text, size) <= maxWidth) return size;
  }
  return 44;
}

const esc = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

function card({ eyebrow, title, body, footer, cta }) {
  const PAD = 84;
  const MAXW = W - PAD * 2;
  const size = titleSize(title, MAXW);
  const bodyLines = wrap(body, 34, MAXW - 20, 2);

  const titleY = 300;
  const bodyStart = titleY + 68;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <defs>
    <pattern id="grid" width="44" height="44" patternUnits="userSpaceOnUse">
      <path d="M44 0H0V44" fill="none" stroke="${C.border}" stroke-width="1" opacity="0.55"/>
    </pattern>
    <linearGradient id="fade" x1="0" y1="0" x2="0.7" y2="1">
      <stop offset="0" stop-color="#fff" stop-opacity="0.9"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </linearGradient>
    <mask id="gridMask"><rect width="${W}" height="${H}" fill="url(#fade)"/></mask>
  </defs>

  <rect width="${W}" height="${H}" fill="${C.bg}"/>
  <rect width="${W}" height="${H}" fill="url(#grid)" mask="url(#gridMask)"/>
  <rect x="0" y="0" width="10" height="${H}" fill="${C.signal}"/>

  <!-- brand rail -->
  <rect x="${PAD}" y="72" width="8" height="30" fill="${C.signal}"/>
  <text x="${PAD + 22}" y="97" font-family="IBM Plex Sans" font-size="30" font-weight="600" fill="${C.text}">CryptoLab</text>
  <text x="${PAD + 22 + Math.round(widthOf('CryptoLab', 30)) + 26}" y="96" font-family="IBM Plex Mono" font-size="20" fill="${C.dim}">${esc(TAGLINE)}</text>
  <rect x="${PAD}" y="128" width="${MAXW}" height="1" fill="${C.border}"/>

  <text x="${PAD}" y="212" font-family="IBM Plex Mono" font-size="24" font-weight="500" letter-spacing="3" fill="${C.signal}">${esc(eyebrow)}</text>

  <text x="${PAD}" y="${titleY}" font-family="IBM Plex Sans" font-size="${size}" font-weight="600" fill="${C.text}" letter-spacing="-1.5">${esc(title)}</text>

  ${bodyLines
    .map(
      (line, i) =>
        `<text x="${PAD}" y="${bodyStart + i * 48}" font-family="IBM Plex Sans" font-size="34" fill="${C.muted}">${esc(line)}</text>`,
    )
    .join('\n  ')}

  <rect x="${PAD}" y="${H - 106}" width="${MAXW}" height="1" fill="${C.border}"/>
  <text x="${PAD}" y="${H - 56}" font-family="IBM Plex Mono" font-size="22" fill="${C.dim}">${esc(footer)}</text>
${ctaMark(cta)}
</svg>`;
}

/*
 * A call to action, filled in the signal colour at the bottom-right. Share
 * cards that are only a title and a sentence read as a banner; the button shape
 * is what makes a preview look clickable, and it is the one thing the scrapers'
 * own linting flags when it is missing.
 */
function ctaMark(label) {
  if (!label) return '';
  const PAD = 84;
  const fs = 26;
  const textW = Math.round(widthOf(label, fs));
  /* The arrow is drawn, not typed: the latin font subsets carry no U+2192 and
     resvg renders a tofu box for it. */
  const arrowW = 24;
  const w = textW + 18 + arrowW + 52;
  const h = 56;
  const x = W - PAD - w;
  const y = H - 106 + 20;
  const ax = x + 26 + textW + 18;
  const ay = y + h / 2;
  const ink = '#04120f';
  return `  <rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="${C.signal}"/>
  <text x="${x + 26}" y="${y + 37}" font-family="IBM Plex Sans" font-size="${fs}" font-weight="600" fill="${ink}">${esc(label)}</text>
  <path d="M${ax} ${ay}h${arrowW}m-9-9 9 9-9 9" fill="none" stroke="${ink}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`;
}

function render(svg, fontPaths, file) {
  const png = new Resvg(svg, {
    fitTo: { mode: 'width', value: W },
    font: {
      fontFiles: fontPaths,
      defaultFontFamily: 'IBM Plex Sans',
      sansSerifFamily: 'IBM Plex Sans',
      monospaceFamily: 'IBM Plex Mono',
      loadSystemFonts: false,
    },
  })
    .render()
    .asPng();
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, png);
  return png.length;
}

const server = await createServer({
  server: { middlewareMode: true },
  appType: 'custom',
  logLevel: 'error',
});

try {
  const { algorithms, CATEGORIES } = await server.ssrLoadModule('/src/core/registry.ts');
  ({ SITE_TAGLINE: TAGLINE } = await server.ssrLoadModule('/src/core/site.ts'));
  const { dir: fontDir, paths: fonts } = await loadFonts();

  const FOOTER = 'Step-by-step walkthrough · Live playground';
  let bytes = 0;

  bytes += render(
    card({
      eyebrow: 'AN INTERACTIVE CRYPTOGRAPHY LAB',
      title: 'Real ciphers, one step at a time',
      body: `${algorithms.length} algorithms, from Caesar to lattice signatures, each running real cryptographic logic in your browser.`,
      footer: `${algorithms.length} algorithms · ${CATEGORIES.length} families · Classical to post-quantum`,
      cta: 'Explore the lab',
    }),
    fonts,
    join(OUT, 'home.png'),
  );
  console.log(`  ${OUT}/home.png`);

  for (const a of algorithms) {
    const family = CATEGORIES.find((c) => c.id === a.meta.category)?.title ?? a.meta.category;
    bytes += render(
      card({
        eyebrow: [family.toUpperCase(), a.meta.era].filter(Boolean).join('  ·  '),
        title: a.meta.name,
        body: a.content.tagline,
        footer: FOOTER,
        cta: `Open ${a.meta.name.length > 14 ? 'the walkthrough' : a.meta.name}`,
      }),
      fonts,
      join(OUT, 'a', `${a.meta.id}.png`),
    );
    console.log(`  ${OUT}/a/${a.meta.id}.png`);
  }

  rmSync(fontDir, { recursive: true, force: true });
  console.log(
    `\n${algorithms.length + 1} cards written (${(bytes / 1024 / 1024).toFixed(2)} MB total).`,
  );

  /*
   * Raster icons from the same favicon source. iOS ignores SVG favicons and
   * the web manifest wants concrete sizes, so these three cover the cases an
   * SVG cannot: the home-screen icon and the two manifest entries.
   */
  const favicon = readFileSync('public/favicon.svg', 'utf8');
  for (const size of [180, 192, 512]) {
    const png = new Resvg(favicon, { fitTo: { mode: 'width', value: size } })
      .render()
      .asPng();
    const name = size === 180 ? 'apple-touch-icon.png' : `icon-${size}.png`;
    writeFileSync(join('public', name), png);
    console.log(`  public/${name}`);
  }
} finally {
  await server.close();
}
