/**
 * Fails the build if any prerendered page points at a share image that is not
 * in the output, or if a page is missing SEO tags entirely.
 *
 * The cards are generated by hand (`pnpm og`) and committed, which means the
 * one way they can go wrong is someone adding an algorithm and not regenerating
 * them. Rather than discovering that when a link previews as a broken image,
 * this checks every emitted page against the emitted files and says exactly
 * which command fixes it.
 *
 * Runs as part of `pnpm build`.
 */

import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const DIST = 'dist';

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (name.endsWith('.html')) out.push(full);
  }
  return out;
}

const pages = walk(DIST);
if (pages.length === 0) {
  console.error('verify-og: no prerendered HTML found in dist/');
  process.exit(1);
}

const problems = [];

for (const file of pages) {
  const route = '/' + relative(DIST, file).split(sep).join('/');
  const html = readFileSync(file, 'utf8');

  const required = [
    ['<title>', /<title[^>]*>[^<]+<\/title>/],
    ['meta description', /<meta[^>]+name="description"[^>]+content="[^"]+"/],
    ['canonical', /<link[^>]+rel="canonical"[^>]+href="https?:\/\/[^"]+"/],
    ['og:title', /<meta[^>]+property="og:title"[^>]+content="[^"]+"/],
    ['og:image', /<meta[^>]+property="og:image"[^>]+content="[^"]+"/],
  ];
  for (const [label, re] of required) {
    if (!re.test(html)) problems.push(`${route}: missing ${label}`);
  }

  /*
   * Length ceilings, with a little headroom over where each surface actually
   * truncates: Google cuts a description around 155-160 and a title around 60,
   * and social previews cut a description nearer 125 on mobile. These are worth
   * failing on rather than warning about, because nobody reads build warnings
   * and a clipped description is invisible until someone shares the link.
   */
  const limits = [
    ['description', /<meta[^>]+name="description"[^>]+content="([^"]*)"/, 160],
    ['og:description', /<meta[^>]+property="og:description"[^>]+content="([^"]*)"/, 130],
    ['title', /<title[^>]*>([^<]*)<\/title>/, 75],
  ];
  for (const [label, re, max] of limits) {
    const value = html.match(re)?.[1] ?? '';
    // Entities count as one character to a search engine, not as `&amp;`.
    const length = value.replace(/&[a-z]+;|&#\d+;/gi, 'x').length;
    if (length > max) {
      problems.push(`${route}: ${label} is ${length} characters, over the ${max} limit`);
    }
  }

  const image = html.match(/<meta[^>]+property="og:image"[^>]+content="([^"]+)"/)?.[1];
  if (image) {
    // og:image is absolute; map it back to the file the deploy will serve.
    const path = image.replace(/^https?:\/\/[^/]+/, '');
    if (!existsSync(join(DIST, path))) {
      problems.push(`${route}: og:image ${path} is not in the build — run \`pnpm og\``);
    }
  }
}

/* The manifest icons are referenced by path from a JSON file nothing type
   checks, so they get the same treatment. */
for (const asset of ['favicon.svg', 'apple-touch-icon.png', 'icon-192.png', 'icon-512.png', 'site.webmanifest', 'robots.txt']) {
  if (!existsSync(join(DIST, asset))) problems.push(`missing /${asset} in the build`);
}

if (problems.length) {
  console.error(`\nverify-og: ${problems.length} problem(s)\n`);
  for (const p of problems) console.error(`  ${p}`);
  console.error('');
  process.exit(1);
}

console.log(
  `SEO verified across ${pages.length} pages (tags, lengths, canonicals, og:image files).`,
);
